### ISSUE TITLE
Could you please update it to Rust 1.17?

### ISSUE THREAD

**Issue by C-Bouthoorn** [bluss/scopeguard#12]
This package doesn't work anymore on the latest Rust version, which is a shame.
Trying to build it, gives the following error

```
error: expected expression, found statement (`let`)
 --> <defer macros>:1:21
  |
1 | ( $ e : expr ) => { let _guard = $ crate :: guard ( (  ) , | _ | $ e ) ; }
  |                     ^^^
  |
  = note: variable declaration using `let` is a statement
```

**Comment by bluss** [comment]
Seems like a breaking change in Rust. First we must understand why and see if it's a bug that needs to be fixed.

**Comment by bluss** [comment]
Scopeguard's tests pass with `rustc 1.17.0-nightly (a559452b0 2017-03-17)`

Do you have an example of code that does not compile?

**Comment by C-Bouthoorn** [comment]
This code failed to compile for me:

```
#[macro_use(defer)]
extern crate scopeguard;

fn main() {
    defer! (
        println!("Hello World!")
    )
}
```

**Comment by bluss** [comment]
Did it compile in previous versions?

**Comment by C-Bouthoorn** [comment]
I have no idea, this is the first time I'm using this package.

**Comment by bluss** [comment]
This is not a bug then

```rust
#[macro_use(defer)]
extern crate scopeguard;

fn main() {
    defer! {
        println!("Hello World!")
    }
}
```
works fine in Rust 1.16 and nightly. Note the { }.

**Comment by C-Bouthoorn** [comment]
Ah, my bad. Thanks!
