### ISSUE TITLE
Document why guard closure is FnMut, not FnOnce

### ISSUE THREAD

**Issue by jonhoo** [bluss/scopeguard#15]
The documentation states that

> The guard's closure will be called with a mut ref to the held value in the destructor. It's called only once.

yet `ScopeGuard` takes an `F where F: FnMut(&mut T)`. What is the reason for not allowing `F` to be `FnOnce`?

**Comment by tormol** [comment]
The inability to move or consume fields inside the `Drop` impl.

One workaround would be to [wrap them in an `Option`](https://github.com/bluss/scopeguard/pull/9/files) but that PR was rejected.  
Today it could be done with the zero-cost `ManuallyDrop`, although that would require `unsafe` code.

**Comment by jonhoo** [comment]
I actually think it's probably okay for it to be `FnMut` (though `FnOnce` makes more intuitive sense to me), I'd just like to see the reason for the difference stated in the docs :)
