### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by davidkazlauskas** [bluss/scopeguard#2]
I like this scope guard in rust, I'd like it to have few more features though (I wrote scope guard in C++ and I miss those):

1. Add an option to dismiss guard (for instance, if all actions succeed sequentially, call .dismiss() so that guard wouldn't be called).
2. Add an option to fire scope guard right away (of course, then it doesn't fire on destructor), for fine grained control and perf reasons. (For instance, we open file with fopen, we read it's contents once, we don't need handle anymore, but scope has not ended yet so it will only be closed on destructor, but we could fire scope guard right after we don't need file handle.)

Reference C++ implementation:

```
template <class T>
struct ScopeGuard {
    ScopeGuard(T&& function) :
        _use(true), _f(std::move(function))
    {}

    void dismiss() {
        _use = false;
    }

    void fire() {
        assert( _use == true &&
            "Can only fire undismissed scope guard." );
        _use = false;
        _f();
    }

    ~ScopeGuard() {
        if (_use) {
            _f();
        }
    }

private:
    bool _use;
    T _f;
};

template <class T>
auto makeScopeGuard(T&& t)
    -> ScopeGuard< typename std::decay<T>::type >
{
    typedef typename std::decay<T>::type DecT;
    return ScopeGuard<DecT>(std::forward<T>(t));
}
```

**Comment by bluss** [comment]
Thank you for the feedback. I don't think the proposed features apply that well to the current `Guard` since it also owns a value. Maybe a consuming `dismiss` fits better. Something like `fn dismiss(self) -> T`.

**Comment by bluss** [comment]
The fire right away could be done with just `drop(guard)` as it is.

A different implementation may use more c++-like dismiss and fire methods.

**Comment by davidkazlauskas** [comment]
"I don't think the proposed features apply that well to the current Guard since it also owns a value."

Yeah, I might agree here. I guess this would be a different kind of scope guard than what I have.

I didn't think about drop but I would imagine calling drop wouldn't be instantly obvious what it does (if someone, say, doesn't know about scope guards or did not lookup variable type yet).

A also I see your scope guard is probably little more performant because it doesn't have a boolean to say whether it was fired.

So, I guess these scope guards might be for different tasks altogether.
