### ISSUE TITLE
Is it able to support async calling?

### ISSUE THREAD

**Issue by kvzn** [bluss/scopeguard#29]
Something like:

```rust
defer! {
    pool.close().await
}
```

**Comment by Amanieu** [comment]
This isn't currently possible because Rust doesn't support async Drop. For more details see https://boats.gitlab.io/blog/post/poll-drop/.

**Comment by kvzn** [comment]
Got it, thank you!

**Comment by huntc** [comment]
Just came across this... Wouldn't it depend on the executor you're running? For example, with Tokio:

```rust
let executor = Handle::current();
defer!({
    executor.spawn({
        async {
            // Do some async cleanup
        }
    });
});
```

The failure scenario here is that spawn will fail to spawn if the executor has been shut down... but then that's ok.

**Comment by BratSinot** [comment]
> Just came across this... Wouldn't it depend on the executor you're running? For example, with Tokio:
> 
> ```rust
> let executor = Handle::current();
> defer!({
>     executor.spawn({
>         async {
>             // Do some async cleanup
>         }
>     });
> });
> ```
> 
> The failure scenario here is that spawn will fail to spawn if the executor has been shut down... but then that's probably ok.

`spawn` not in option in case, then `Self` not `'static`.
