### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by RalfJung** [bluss/scopeguard#40]
https://github.com/bluss/scopeguard/pull/25 (seemingly unintentionally) fixed a possible aliasing rule violation in scopeguard. The aliasing rules are not clear yet, of course, but Miri will show errors for scopeguard before that fix when references in fields of structs are all properly tracked -- something that we are soon going to [enable at least for some structs](https://github.com/rust-lang/miri/pull/2636) since it is needed to properly reflect all the `noalias` we emit for LLVM.

It would be great to see a new release of scopeguard, so that people using scopeguard can use Miri on their crates without having to disable some of the checks. :)

**Comment by RalfJung** [comment]
I do hope to enable full handling of "references passed in structs" in Miri Soon (TM), which will likely cause errors with the currently released scopeguard that are fixed by #25.

@bluss any chance of a release? It's been a while since that MR merged, would be good to get that fix out to users. :)

**Comment by Amanieu** [comment]
Published v1.2.0.

**Comment by RalfJung** [comment]
Thanks a lot. :)
