### ISSUE TITLE
[IDEA] move ownership to ScopeGuard 

### ISSUE THREAD

**Issue by hkoosha** [bluss/scopeguard#44]
Hey!

In response to the [Perhaps Rust needs "defer"](https://gaultier.github.io/blog/perhaps_rust_needs_defer.html) post, is it ok if I open a PR that implements full ownership in ScopeGuard with a new macro (which right now I can only think of `deferred!`) that returns the guard and it's responsibility of caller to hold to it? Behaving pretty much like a `Box`.

```rust
macro_rules! defered {
    ($v:ident, $($t:block)*) => {
        $crate::guard($v, |mut $v| { $($t)* })
    };
}
```

**Comment by bluss** [comment]
What's new in this suggestion? Compare with what's already possible, see example (1) here https://docs.rs/scopeguard/latest/scopeguard/#1-the-guard-owns-a-file

**Comment by hkoosha** [comment]
Indeed, that was just a bit of confusion on my side; the macro above is just an unnecessary indirection over the existing `guard()` method.
