### ISSUE TITLE
Why store a value when the closure could just capture it?

### ISSUE THREAD

**Issue by tormol** [bluss/scopeguard#6]
What does
```
let foo = "foo";
guard(foo, |foo| bar(foo) );
...
```
allow that
```
let foo = "foo";
guard(|| bar(&mut foo) );
...
```
doesn't?

**Comment by bluss** [comment]
The deref impl, which allows the stored value to be mutated both during it is live, as well as in the destructor.

**Comment by tormol** [comment]
Oh, I didn't think of that.
